### ISSUE TITLE
ATP module is not graalvm native image compliant

### ISSUE THREAD

**Issue by pgressa** [micronaut-projects/micronaut-oracle-cloud#152]
```
 __  __ _                                  _   
|  \/  (_) ___ _ __ ___  _ __   __ _ _   _| |_ 
| |\/| | |/ __| '__/ _ \| '_ \ / _` | | | | __|
| |  | | | (__| | | (_) | | | | (_| | |_| | |_ 
|_|  |_|_|\___|_|  \___/|_| |_|\__,_|\__,_|\__|
  Micronaut (v2.4.2)

16:52:34.901 [main] INFO  com.oracle.bmc.Services - Registering new service: Services.BasicService(serviceName=DATABASE, serviceEndpointPrefix=database, serviceEndpointTemplate=https://database.{region}.{secondLevelDomain})
16:52:34.904 [main] INFO  com.oracle.bmc.util.JavaRuntimeUtils - Determined JRE version as Unknown
16:52:34.904 [main] WARN  c.o.bmc.http.DefaultConfigurator - Using an unknown runtime, calls may not work
16:52:34.904 [main] INFO  c.o.bmc.http.DefaultConfigurator - Setting connector provider to HttpUrlConnectorProvider
16:52:34.904 [main] INFO  com.oracle.bmc.Region - Loaded service 'DATABASE' endpoint mappings: {US_PHOENIX_1=https://database.us-phoenix-1.oraclecloud.com}
16:52:34.904 [main] INFO  c.oracle.bmc.database.DatabaseClient - Setting endpoint to https://database.us-phoenix-1.oraclecloud.com
16:52:34.904 [main] ERROR io.micronaut.runtime.Micronaut - Error starting Micronaut server: Error instantiating bean of type  [io.micronaut.oraclecloud.atp.jdbc.OracleWalletArchiveProvider]

Message: java.lang.ClassNotFoundException: org.glassfish.jersey.internal.RuntimeDelegateImpl
Path Taken: new HikariPoolConfigurationListener([OracleWalletArchiveProvider walletArchiveProvider],BeanLocator beanLocator) --> new OracleWalletArchiveProvider([Database databaseClient])
io.micronaut.context.exceptions.BeanInstantiationException: Error instantiating bean of type  [io.micronaut.oraclecloud.atp.jdbc.OracleWalletArchiveProvider]

Message: java.lang.ClassNotFoundException: org.glassfish.jersey.internal.RuntimeDelegateImpl
Path Taken: new HikariPoolConfigurationListener([OracleWalletArchiveProvider walletArchiveProvider],BeanLocator beanLocator) --> new OracleWalletArchiveProvider([Database databaseClient])
        at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1970)
        at io.micronaut.context.DefaultBeanContext.createAndRegisterSingletonInternal(DefaultBeanContext.java:2724)
        at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:2710)
        at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:2382)
        at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:2356)
        at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1261)
        at io.micronaut.context.AbstractBeanDefinition.getBeanForConstructorArgument(AbstractBeanDefinition.java:1012)
        at io.micronaut.oraclecloud.atp.jdbc.$OracleWalletArchiveProviderDefinition.build(Unknown Source)
        at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1943)
        at io.micronaut.context.DefaultBeanContext.createAndRegisterSingletonInternal(DefaultBeanContext.java:2724)
        at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:2710)
        at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:2382)
        at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:2356)
        at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1261)
        at io.micronaut.context.AbstractBeanDefinition.getBeanForConstructorArgument(AbstractBeanDefinition.java:1012)
        at io.micronaut.oraclecloud.atp.jdbc.hikari.$HikariPoolConfigurationListenerDefinition.build(Unknown Source)
        at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1943)
        at io.micronaut.context.DefaultBeanContext.createAndRegisterSingletonInternal(DefaultBeanContext.java:2724)
        at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:2710)
        at io.micronaut.context.DefaultBeanContext.initializeEventListeners(DefaultBeanContext.java:1499)
        at io.micronaut.context.DefaultBeanContext.readAllBeanDefinitionClasses(DefaultBeanContext.java:2856)
        at io.micronaut.context.DefaultBeanContext.start(DefaultBeanContext.java:231)
        at io.micronaut.context.DefaultApplicationContext.start(DefaultApplicationContext.java:165)
        at io.micronaut.runtime.Micronaut.start(Micronaut.java:71)
        at io.micronaut.runtime.Micronaut.run(Micronaut.java:311)
        at io.micronaut.runtime.Micronaut.run(Micronaut.java:297)
        at com.example.Application.main(Application.java:8)
Caused by: java.lang.RuntimeException: java.lang.ClassNotFoundException: org.glassfish.jersey.internal.RuntimeDelegateImpl
        at javax.ws.rs.ext.RuntimeDelegate.findDelegate(RuntimeDelegate.java:129)
        at javax.ws.rs.ext.RuntimeDelegate.getInstance(RuntimeDelegate.java:96)
        at javax.ws.rs.core.UriBuilder.newInstance(UriBuilder.java:72)
        at javax.ws.rs.core.UriBuilder.fromUri(UriBuilder.java:96)
        at org.glassfish.jersey.client.JerseyWebTarget.<init>(JerseyWebTarget.java:48)
        at org.glassfish.jersey.client.JerseyClient.target(JerseyClient.java:274)
        at org.glassfish.jersey.client.JerseyClient.target(JerseyClient.java:56)
        at com.oracle.bmc.http.internal.RestClient.setEndpoint(RestClient.java:83)
        at com.oracle.bmc.database.DatabaseClient.setEndpoint(DatabaseClient.java:403)
        at com.oracle.bmc.database.DatabaseClient.setRegion(DatabaseClient.java:420)
        at com.oracle.bmc.database.DatabaseClient.<init>(DatabaseClient.java:332)
        at com.oracle.bmc.database.DatabaseClient.<init>(DatabaseClient.java:217)
        at com.oracle.bmc.database.DatabaseClient$Builder.build(DatabaseClient.java:388)
        at io.micronaut.oraclecloud.clients.database.DatabaseClientFactory.build(DatabaseClientFactory.java:43)
        at io.micronaut.oraclecloud.clients.database.$DatabaseClientFactory$Build1Definition.build(Unknown Source)
        at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1943)
        ... 26 common frames omitted
Caused by: java.lang.ClassNotFoundException: org.glassfish.jersey.internal.RuntimeDelegateImpl
        at com.oracle.svm.core.hub.ClassForNameSupport.forName(ClassForNameSupport.java:60)
        at java.lang.Class.forName(DynamicHub.java:1247)
        at javax.ws.rs.ext.FactoryFinder.newInstance(FactoryFinder.java:87)
        at javax.ws.rs.ext.FactoryFinder.find(FactoryFinder.java:185)
        at javax.ws.rs.ext.RuntimeDelegate.findDelegate(RuntimeDelegate.java:111)
        ... 41 common frames omitted

```

**Comment by pgressa** [comment]
Fixed by https://github.com/micronaut-projects/micronaut-oracle-cloud/pull/139
