### ISSUE TITLE
Add a new OCI streaming module that reconfigures configure / fixes health check

### ISSUE THREAD

**Issue by graemerocher** [micronaut-projects/micronaut-oracle-cloud#180]
Currently it is too complex to craft the configuration to connect to OCI streaming 

There should be a OCI streaming module that depends on Kafka and auto-configures it plus fixes the health endpoint which does not work and report

```
11:06:37.332 [scheduled-executor-thread-1] ERROR i.m.m.health.indicator.HealthResult - Health indicator [kafka] reported exception: java.lang.NullPointerException: The future returned null
java.lang.NullPointerException: The future returned null
	at io.reactivex.internal.operators.flowable.FlowableFromFuture.subscribeActual(FlowableFromFuture.java:51)
	at io.reactivex.Flowable.subscribe(Flowable.java:14935)

```

**Comment by dmeibusch** [comment]
Agreed, in particular the Kafka configuration documentation to connect as resource or instance principal to Streaming was difficult to find for us.
