### ISSUE TITLE
OCI streaming fails on GraalVM native image

### ISSUE THREAD

**Issue by graemerocher** [micronaut-projects/micronaut-oracle-cloud#183]
Building a native image works but it fails to connect on native image with:

```
Caused by: javax.security.auth.callback.UnsupportedCallbackException: Could not login: the client is being asked for a password, but the Kafka client code does not currently support obtaining a password from the user.
	at org.apache.kafka.common.security.authenticator.SaslClientCallbackHandler.handle(SaslClientCallbackHandler.java:73)
	at com.sun.security.sasl.ClientFactoryImpl.getUserInfo(ClientFactoryImpl.java:136)
	... 33 common frames omitted
```

Example:

[books-events.zip](https://github.com/micronaut-projects/micronaut-oracle-cloud/files/6465055/books-events.zip)

**Comment by pgressa** [comment]
This is already fixed.
