### ISSUE TITLE
Micronaut 3.0.0 changes for RXJAVA break OCI Vault

### ISSUE THREAD

**Issue by recursivecodes** [micronaut-projects/micronaut-oracle-cloud#305]
### Expected Behavior

OCI Vault Feature should work out of the box without adding a dependency.

Workaround: 

Add to `build.gradle`:

```
implementation("io.micronaut.rxjava2:micronaut-rxjava2")
```

### Actual Behaviour

Application throws:

```
12:00:18.987 [main] ERROR io.micronaut.runtime.Micronaut - Error starting Micronaut server: io/reactivex/Flowable
java.lang.NoClassDefFoundError: io/reactivex/Flowable
	at io.micronaut.discovery.oraclecloud.vault.config.OracleCloudVaultConfigurationClient.getPropertySources(OracleCloudVaultConfigurationClient.java:176)
	at io.micronaut.discovery.config.DefaultCompositeConfigurationClient.lambda$getPropertySources$0(DefaultCompositeConfigurationClient.java:64)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at io.micronaut.discovery.config.DefaultCompositeConfigurationClient.getPropertySources(DefaultCompositeConfigurationClient.java:65)
	at io.micronaut.discovery.client.config.DistributedPropertySourceLocator.findPropertySources(DistributedPropertySourceLocator.java:76)
	at io.micronaut.context.DefaultApplicationContext$RuntimeConfiguredEnvironment.readPropertySourceList(DefaultApplicationContext.java:733)
	at io.micronaut.context.env.DefaultEnvironment.readPropertySources(DefaultEnvironment.java:403)
	at io.micronaut.context.env.DefaultEnvironment.start(DefaultEnvironment.java:265)
	at io.micronaut.context.DefaultApplicationContext$RuntimeConfiguredEnvironment.start(DefaultApplicationContext.java:719)
	at io.micronaut.context.DefaultApplicationContext$RuntimeConfiguredEnvironment.start(DefaultApplicationContext.java:688)
	at io.micronaut.context.DefaultApplicationContext.startEnvironment(DefaultApplicationContext.java:229)
	at io.micronaut.context.DefaultApplicationContext.start(DefaultApplicationContext.java:181)
	at io.micronaut.runtime.Micronaut.start(Micronaut.java:72)
	at io.micronaut.runtime.Micronaut.run(Micronaut.java:313)
	at io.micronaut.runtime.Micronaut.run(Micronaut.java:299)
	at codes.recursive.Application.main(Application.java:8)
Caused by: java.lang.ClassNotFoundException: io.reactivex.Flowable
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
Caused by: java.lang.ClassNotFoundException: io.reactivex.Flowable

	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 22 common frames omitted

> Task :run FAILED

```

### Steps To Reproduce

Create a new application that uses OCI vault and run it.

### Environment Information

N/A

### Version

3.1.4

**Comment by graemerocher** [comment]
Fixed by https://github.com/micronaut-projects/micronaut-oracle-cloud/commit/739e6275c5be1011979732e688eb4325a26c6a50
