### ISSUE TITLE
Exception when running `java -jar`: "Invalid signature file digest for Manifest main attributes"

### ISSUE THREAD

**Issue by alvarosanchez** [micronaut-projects/micronaut-oracle-cloud#401]
It appears that some of the `io.micronaut.oraclecloud:micronaut-oraclecloud-vault` transitive dependencies are signed JARs with signatures inside. When shading them into a fat JAR, those signatures are included, but they don't match the fat JAR's signature, so the following exception is thrown when running with `java -jar`:

```
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.SecurityException: Invalid signature file digest for Manifest main attributes
        at java.base/sun.security.util.SignatureFileVerifier.processImpl(SignatureFileVerifier.java:340)
        at java.base/sun.security.util.SignatureFileVerifier.process(SignatureFileVerifier.java:282)
        at java.base/java.util.jar.JarVerifier.processEntry(JarVerifier.java:321)
        at java.base/java.util.jar.JarVerifier.update(JarVerifier.java:234)
        at java.base/java.util.jar.JarFile.initializeVerifier(JarFile.java:762)
        at java.base/java.util.jar.JarFile.ensureInitialization(JarFile.java:1033)
        at java.base/java.util.jar.JavaUtilJarAccessImpl.ensureInitialization(JavaUtilJarAccessImpl.java:72)
        at java.base/jdk.internal.loader.URLClassPath$JarLoader$2.getManifest(URLClassPath.java:883)
        at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:848)
        at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:760)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:681)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:639)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:467)
        at java.base/sun.launcher.LauncherHelper.loadMainClass(LauncherHelper.java:780)
```

The solution when using Maven is to exclude the signature files, as described here: https://stackoverflow.com/a/6743609/2923710

This likely affects Gradle too, but it is yet to be checked.

I see 2 things we could do:

1. Change the [`oracle-cloud-vault` feature in Micronaut Launch](https://github.com/micronaut-projects/micronaut-starter/blob/3.6.x/starter-core/src/main/java/io/micronaut/starter/feature/oraclecloud/OracleCloudVault.java) to include the necessary Shade/Shadow plugin configuration.
2. Change the [`micronaut-cloud-secrets-oracle` guide](https://github.com/micronaut-projects/micronaut-guides/blob/master/guides/micronaut-cloud-secrets-oracle/micronaut-cloud-secrets-oracle.adoc) to mention the configuration to be added.

**Comment by alvarosanchez** [comment]
The workaround is to add the following to the POM:

```xml
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-shade-plugin</artifactId>
        <executions>
          <execution>
            <id>default-shade</id>
            <configuration>
              <filters>
                <filter>
                  <artifact>*:*</artifact>
                  <excludes>
                    <exclude>META-INF/*.SF</exclude>
                    <exclude>META-INF/*.DSA</exclude>
                    <exclude>META-INF/*.RSA</exclude>
                  </excludes>
                </filter>
              </filters>
            </configuration>
          </execution>
        </executions>
      </plugin>
```
