### ISSUE TITLE
Investigate ADDITIONAL_MODELS generation

### ISSUE THREAD

**Issue by yawkat** [micronaut-projects/micronaut-oracle-cloud#669]
### Issue description

A user reported the following error:

```
Caused by: io.micronaut.core.beans.exceptions.IntrospectionException: No bean introspection available for type [class com.oracle.bmc.auth.internal.JWK]. Ensure the class is annotated with io.micronaut.core.annotation.Introspected
```

It seems JWK is not included in the ADDITIONAL_MODELS Set, and is not generated. I'm not sure if adding it to the Set would be enough though, since the auth module does not seem to be processed at all.

I've also tried to find some of the other introspections that are supposed to be generated by ADDITIONAL_MODELS, and they appear to be missing.

**Comment by yawkat** [comment]
```
Exception in thread "main" com.oracle.bmc.model.BmcException: Error returned by ListInstances operation in Compute service.(-1, null, false) Unknown error
Timestamp: 2023-08-11T08:56:50.438Z
Client version: Oracle-JavaSDK/3.20.0
Request Endpoint: https://iaas.us-phoenix-1.oraclecloud.com/20160918/instances?compartmentId=xxx
Troubleshooting Tips: See https://docs.oracle.com/en-us/iaas/Content/API/References/apierrors.htm#apierrors_-1__-1_ for more information about resolving this error
Also see https://docs.oracle.com/iaas/api/#/en/iaas/20160918/Instance/ListInstances for details on this operation's requirements.
To get more info on the failing request, you can enable debug level logs as mentioned in `Using SLF4J for Logging section` in https://docs.oracle.com/en-us/iaas/Content/API/SDKDocs/javasdkconfig.htm.
If you are unable to resolve this Compute issue, please contact Oracle support and provide them this full error message.
        at com.oracle.bmc.model.BmcException.createClientSide(BmcException.java:221)
        at com.oracle.bmc.http.internal.ClientCall.callSync(ClientCall.java:1050)
        at com.oracle.bmc.core.ComputeClient.listInstances(ComputeClient.java:2495)
xxx
Caused by: java.lang.IllegalArgumentException: Unable to process JSON body
        at io.micronaut.oraclecloud.httpclient.netty.NettyHttpRequest.body(NettyHttpRequest.java:132)
        at com.oracle.bmc.http.internal.ClientCall.hasBody(ClientCall.java:202)
        at com.oracle.bmc.auth.internal.X509FederationClient.getSecurityTokenFromServer(X509FederationClient.java:387)
        at com.oracle.bmc.auth.internal.X509FederationClient.refreshAndGetSecurityTokenInner(X509FederationClient.java:302)
        at com.oracle.bmc.auth.internal.X509FederationClient.getSecurityToken(X509FederationClient.java:223)
        at com.oracle.bmc.auth.AbstractRequestingAuthenticationDetailsProvider.getKeyId(AbstractRequestingAuthenticationDetailsProvider.java:88)
        at com.oracle.bmc.http.signing.internal.DefaultRequestSignerFactory$1.get(DefaultRequestSignerFactory.java:71)
        at com.oracle.bmc.http.signing.internal.DefaultRequestSignerFactory$1.get(DefaultRequestSignerFactory.java:68)
        at com.oracle.bmc.http.signing.internal.RequestSignerImpl.signRequest(RequestSignerImpl.java:130)
        at com.oracle.bmc.http.signing.internal.RequestSignerImpl.signRequest(RequestSignerImpl.java:107)
        at com.oracle.bmc.http.internal.AuthnClientFilter.intercept(AuthnClientFilter.java:50)
        at io.micronaut.oraclecloud.httpclient.netty.NettyHttpRequest.execute(NettyHttpRequest.java:256)
        at com.oracle.bmc.http.internal.ClientCall.callAsyncImpl(ClientCall.java:973)
        at com.oracle.bmc.retrier.BmcGenericRetrier.doFunctionCall(BmcGenericRetrier.java:175)
        at com.oracle.bmc.retrier.BmcGenericRetrier.doFunctionCallAsync(BmcGenericRetrier.java:181)
        at com.oracle.bmc.retrier.BmcGenericRetrier.lambda$executeAsync$3(BmcGenericRetrier.java:119)
        at com.oracle.bmc.waiter.GenericWaiter.executeAsync(GenericWaiter.java:109)
        at com.oracle.bmc.waiter.GenericWaiter.executeAsync(GenericWaiter.java:98)
        at com.oracle.bmc.retrier.BmcGenericRetrier.executeAsync(BmcGenericRetrier.java:112)
        at com.oracle.bmc.http.internal.ClientCall.callAsyncTokenRefresh(ClientCall.java:914)
        at com.oracle.bmc.retrier.BmcGenericRetrier.doFunctionCall(BmcGenericRetrier.java:175)
        at com.oracle.bmc.retrier.BmcGenericRetrier.doFunctionCallAsync(BmcGenericRetrier.java:181)
        at com.oracle.bmc.retrier.BmcGenericRetrier.lambda$executeAsync$3(BmcGenericRetrier.java:119)
        at com.oracle.bmc.waiter.GenericWaiter.executeAsync(GenericWaiter.java:109)
        at com.oracle.bmc.waiter.GenericWaiter.executeAsync(GenericWaiter.java:98)
        at com.oracle.bmc.retrier.BmcGenericRetrier.executeAsync(BmcGenericRetrier.java:112)
        at com.oracle.bmc.http.internal.ClientCall.callAsyncWithRetrier(ClientCall.java:906)
        at com.oracle.bmc.http.internal.ClientCall.callAsync0(ClientCall.java:853)
        at com.oracle.bmc.http.internal.ClientCall.callSync(ClientCall.java:1046)
        ... 3 more
Caused by: io.micronaut.serde.exceptions.SerdeException: No serializable introspection present for type X509FederationRequest. Consider adding Serdeable. Serializable annotate to type X509FederationRequest. Alternatively if you are not in control of the project's source code, you can use @SerdeImport(X509FederationRequest.class) to enable serialization of this type.
        at io.micronaut.serde.support.serializers.ObjectSerializer$4.tryToFindSerializer(ObjectSerializer.java:218)
        at io.micronaut.serde.support.serializers.ObjectSerializer$RuntimeTypeSerializer.lambda$getSerializer$0(ObjectSerializer.java:280)
        at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
        at io.micronaut.serde.support.serializers.ObjectSerializer$RuntimeTypeSerializer.getSerializer(ObjectSerializer.java:278)
        at io.micronaut.serde.support.serializers.ObjectSerializer$RuntimeTypeSerializer.serialize(ObjectSerializer.java:245)
        at io.micronaut.serde.jackson.JacksonJsonMapper.writeValue(JacksonJsonMapper.java:114)
        at io.micronaut.serde.jackson.JacksonJsonMapper.writeValue0(JacksonJsonMapper.java:106)
        at io.micronaut.serde.jackson.JacksonJsonMapper.writeValue0(JacksonJsonMapper.java:100)
        at io.micronaut.serde.jackson.JacksonJsonMapper.writeValueAsBytes(JacksonJsonMapper.java:201)
        at io.micronaut.serde.ObjectMappers$2.writeValueAsBytes(ObjectMappers.java:147)
        at io.micronaut.serde.ObjectMapper.writeValueAsString(ObjectMapper.java:39)
        at io.micronaut.oraclecloud.httpclient.netty.NettyHttpRequest.body(NettyHttpRequest.java:130)
        ... 31 more
Caused by: io.micronaut.core.beans.exceptions.IntrospectionException: No serializable introspection present for type X509FederationRequest. Consider adding Serdeable. Serializable annotate to type X509FederationRequest. Alternatively if you are not in control of the project's source code, you can use @SerdeImport(X509FederationRequest.class) to enable serialization of this type.
        at io.micronaut.serde.support.DefaultSerdeIntrospections.getSerializableIntrospection(DefaultSerdeIntrospections.java:102)
        at io.micronaut.serde.support.serializers.SerBean.<init>(SerBean.java:107)
        at io.micronaut.serde.support.serializers.ObjectSerializer.create(ObjectSerializer.java:202)
        at io.micronaut.serde.support.serializers.ObjectSerializer.lambda$getSerBean$0(ObjectSerializer.java:193)
        at io.micronaut.core.util.SupplierUtil$2.get(SupplierUtil.java:79)
        at io.micronaut.serde.support.serializers.ObjectSerializer.getSerBean(ObjectSerializer.java:194)
        at io.micronaut.serde.support.serializers.ObjectSerializer.createSpecificInternal(ObjectSerializer.java:93)
        at io.micronaut.serde.support.serializers.ObjectSerializer.createSpecific(ObjectSerializer.java:86)
        at io.micronaut.serde.jackson.JacksonJsonMapper.writeValue(JacksonJsonMapper.java:112)
        ... 37 more
```
