### ISSUE TITLE
OCI Object Storage "Get Bucket" API call fails when used with GraalVM native image

### ISSUE THREAD

**Issue by nikhmalh** [micronaut-projects/micronaut-oracle-cloud#721]
### Expected Behavior

OCI Object Storage "Get Bucket" call should work properly when used with GraalVM image.

### Actual Behaviour

OCI Object Storage "Get Bucket" API call fails with the following error when used with GraalVM native image:
07:21:43.564 [io-executor-thread-62] ERROR i.m.http.server.RouteExecutor - Unexpected error occurred: Could not get the correct value for enum com.oracle.bmc.objectstorage.requests.GetBucketRequest.Fields
java.lang.IllegalArgumentException: Could not get the correct value for enum com.oracle.bmc.objectstorage.requests.GetBucketRequest.Fields
    at com.oracle.bmc.http.internal.ClientCall.appendListParameter(ClientCall.java:488)
    at com.oracle.bmc.http.internal.ClientCall.appendListQueryParam(ClientCall.java:311)
    at com.oracle.bmc.objectstorage.ObjectStorageClient.getBucket(ObjectStorageClient.java:852)
    at com.oracle.ee.backupsvc.util.oss.OSSUtils.getBucket(OSSUtils.java:240)
    at com.oracle.ee.backupsvc.BackupUserServiceController.getRepositoryAccessorAsUser(BackupUserServiceController.java:698)
    at com.oracle.ee.backupsvc.$BackupUserServiceController$Definition$Intercepted.$$access$$getRepositoryAccessorAsUser(Unknown Source)
    at com.oracle.ee.backupsvc.$BackupUserServiceController$Definition$Exec.dispatch(Unknown Source)
    at io.micronaut.context.AbstractExecutableMethodsDefinition$DispatchedExecutableMethod.invoke(AbstractExecutableMethodsDefinition.java:442)
    at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:128)
    at io.micronaut.transaction.interceptor.TransactionalInterceptor.lambda$intercept$5(TransactionalInterceptor.java:140)
    at io.micronaut.transaction.support.AbstractPropagatedStatusTransactionOperations.lambda$execute$2(AbstractPropagatedStatusTransactionOperations.java:68)
    at io.micronaut.transaction.TransactionCallback.apply(TransactionCallback.java:37)
    at io.micronaut.transaction.support.AbstractTransactionOperations.executeTransactional(AbstractTransactionOperations.java:333)
    at io.micronaut.transaction.support.AbstractTransactionOperations.executeWithNewTransaction(AbstractTransactionOperations.java:318)
    at io.micronaut.transaction.support.AbstractTransactionOperations.executeNew(AbstractTransactionOperations.java:235)
    at io.micronaut.transaction.support.AbstractTransactionOperations.doExecute(AbstractTransactionOperations.java:137)
    at io.micronaut.transaction.support.AbstractTransactionOperations.lambda$doExecute$0(AbstractTransactionOperations.java:122)
    at io.micronaut.data.connection.support.AbstractConnectionOperations.executeWithNewConnection(AbstractConnectionOperations.java:143)
    at io.micronaut.data.connection.support.AbstractConnectionOperations.execute(AbstractConnectionOperations.java:90)
    at io.micronaut.transaction.support.AbstractTransactionOperations.doExecute(AbstractTransactionOperations.java:120)
    at io.micronaut.transaction.support.AbstractPropagatedStatusTransactionOperations.execute(AbstractPropagatedStatusTransactionOperations.java:65)
    at io.micronaut.transaction.interceptor.TransactionalInterceptor.intercept(TransactionalInterceptor.java:140)
    at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:137)
    at com.oracle.ee.backupsvc.$BackupUserServiceController$Definition$Intercepted.getRepositoryAccessorAsUser(Unknown Source)
    at com.oracle.ee.backupsvc.api.AbstractBackupUserServiceController.getRepositoryAccessorAsUserApi(AbstractBackupUserServiceController.java:330)
    at com.oracle.ee.backupsvc.$BackupUserServiceController$Definition$Intercepted.$$access$$getRepositoryAccessorAsUserApi(Unknown Source)
    at com.oracle.ee.backupsvc.$BackupUserServiceController$Definition$Exec.dispatch(Unknown Source)
    at io.micronaut.context.AbstractExecutableMethodsDefinition$DispatchedExecutableMethod.invoke(AbstractExecutableMethodsDefinition.java:442)
    at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:128)
    at io.micronaut.validation.ValidatingInterceptor.validateReturnMicronautValidator(ValidatingInterceptor.java:153)
    at io.micronaut.validation.ValidatingInterceptor.intercept(ValidatingInterceptor.java:139)
    at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:137)
    at com.oracle.ee.backupsvc.$BackupUserServiceController$Definition$Intercepted.getRepositoryAccessorAsUserApi(Unknown Source)
    at com.oracle.ee.backupsvc.$BackupUserServiceController$Definition$Exec.dispatch(Unknown Source)
    at io.micronaut.context.AbstractExecutableMethodsDefinition$DispatchedExecutableMethod.invokeUnsafe(AbstractExecutableMethodsDefinition.java:447)
    at io.micronaut.context.DefaultBeanContext$BeanContextUnsafeExecutionHandle.invokeUnsafe(DefaultBeanContext.java:4187)
    at io.micronaut.web.router.AbstractRouteMatch.execute(AbstractRouteMatch.java:228)
    at io.micronaut.http.context.ServerRequestContext.with(ServerRequestContext.java:74)
    at io.micronaut.http.server.RouteExecutor.executeRouteAndConvertBody(RouteExecutor.java:480)
    at io.micronaut.http.server.RouteExecutor.lambda$callRoute$6(RouteExecutor.java:457)
    at io.micronaut.core.execution.ExecutionFlow.lambda$async$1(ExecutionFlow.java:87)
    at io.micronaut.core.propagation.PropagatedContext.lambda$wrap$3(PropagatedContext.java:211)
    at java.base@21/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
    at java.base@21/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
    at java.base@21/java.lang.Thread.runWith(Thread.java:1596)
    at java.base@21/java.lang.Thread.run(Thread.java:1583)
    at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:833)
    at org.graalvm.nativeimage.builder/com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:211)

### Environment Information

Environment:
Micronaut 4.1.2
GraalVM for JDK21
micronaut-oraclecloud-bmc-objectstorage-3.0.4
oci-java-sdk-objectstorage-3.25.1

### Version

4.1.2

**Comment by nikhmalh** [comment]
This API call works fine normally, but fails when used with GraalVM native image.

**Comment by andriy-dmytruk** [comment]
The issue appears to be in OCI SDK. There is a place in ClientCall that uses reflection directly, therefore causing the error that you see: https://github.com/oracle/oci-java-sdk/blob/2d901e6e7c4775e1cbd4c726b67c04656adc377a/bmc-common/src/main/java/com/oracle/bmc/http/internal/ClientCall.java#L483. I will work on fixing it there.

This issue should temporary be fixable by placing this `reflection-config.json` anywhere in `META-INF/native-image` folder:
```json
[
  {
    "name": "com.oracle.bmc.objectstorage.requests.GetBucketRequest$Fields",
    "methods" : [{ "name" : "getValue", "parameterTypes" : [] }]
  }
]
```
Or alternatively not using the `.fields()` property of the `GetBucketRequest`. The list query parameter is not used often, so you should not see the issue in other places I think.

**Comment by nikhmalh** [comment]
Hi,
I have configured reflection-config.json with the following entry. But still, it is not working.  Please let me know if there is any issue here.
[
  {
    "name": "com.oracle.bmc.objectstorage.requests.GetBucketRequest$Fields",
    "methods" : [{ "name" : "getValue", "parameterTypes" : [] }]
  }
]
